basePath = "Interface\\AddOns\\TwitchEmotes_Giga\\emotes\\";
TwitchEmotes_animation_metadata[basePath .. "peepoRun.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18};
TwitchEmotes_animation_metadata[basePath .. "donkWalk.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "catPls.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Cooking.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MONKE.tga"] = {["nFrames"] = 158, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "SCHIZO.tga"] = {["nFrames"] = 71, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "catYep.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "catNope.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "LETSFUCKINGSHIT.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GAMBA.tga"] = {["nFrames"] = 29, ["frameWidth"] = 32, ["frameHeight"] = 27, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "clam.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "THEVOICES.tga"] = {["nFrames"] = 45, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ppOverheat.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 28, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "HECOOKING.tga"] = {["nFrames"] = 38, ["frameWidth"] = 32, ["frameHeight"] = 31, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "THINKING.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "treeDance.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 20}
TwitchEmotes_animation_metadata[basePath .. "GAGGERS.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "awaree.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "Joeling.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 24}
TwitchEmotes_animation_metadata[basePath .. "donut.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "deadlole.tga"] = {["nFrames"] = 71, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DIEEE.tga"] = {["nFrames"] = 86, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "OFHELL.tga"] = {["nFrames"] = 22, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PotChamp.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 8}
TwitchEmotes_animation_metadata[basePath .. "POGCRAZY.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 8}
TwitchEmotes_animation_metadata[basePath .. "EATO.tga"] = {["nFrames"] = 65, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ChugU.tga"] = {["nFrames"] = 54, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "DESKCHAN.tga"] = {["nFrames"] = 15, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "chickenWalk.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "NAUR.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NOOO.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "JOHNSOULS.tga"] = {["nFrames"] = 81, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "docPls.tga"] = {["nFrames"] = 126, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "RapThis.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "LICKA.tga"] = {["nFrames"] = 58, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "GETALIFE.tga"] = {["nFrames"] = 31, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Tssk.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "borpaSpin.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "pikaMine.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "LondonStyle.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 4}
TwitchEmotes_animation_metadata[basePath .. "DIESOFCRINGE.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "RobPls.tga"] = {["nFrames"] = 50, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Nessie.tga"] = {["nFrames"] = 106, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MODS.tga"] = {["nFrames"] = 86, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Gachi.tga"] = {["nFrames"] = 179, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 40}
TwitchEmotes_animation_metadata[basePath .. "SurefourHittingDaGriddy.tga"] = {["nFrames"] = 179, ["frameWidth"] = 128, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "moon2Lies.tga"] = {["nFrames"] = 26, ["frameWidth"] = 66, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "TAUNTED.tga"] = {["nFrames"] = 88, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SEXO.tga"] = {["nFrames"] = 65, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "PawgChamp.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "MilkTime.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "Goon.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GachiVictory.tga"] = {["nFrames"] = 14, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "gachiCOOL.tga"] = {["nFrames"] = 13, ["frameWidth"] = 29, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 40}
TwitchEmotes_animation_metadata[basePath .. "buttGala.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 7}
TwitchEmotes_animation_metadata[basePath .. "YES.tga"] = {["nFrames"] = 33, ["frameWidth"] = 43, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "NOPE.tga"] = {["nFrames"] = 36, ["frameWidth"] = 40, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Bocchi.tga"] = {["nFrames"] = 32, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Lick.tga"] = {["nFrames"] = 31, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Kissahomie.tga"] = {["nFrames"] = 29, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "dpsCheck.tga"] = {["nFrames"] = 28, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "blobSweating.tga"] = {["nFrames"] = 80, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "BaldiPls.tga"] = {["nFrames"] = 205, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DONOTCUM.tga"] = {["nFrames"] = 46, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "IMGONNACUM.tga"] = {["nFrames"] = 50, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SHEESH.tga"] = {["nFrames"] = 98, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ROFL.tga"] = {["nFrames"] = 40, ["frameWidth"] = 40, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GRATZ.tga"] = {["nFrames"] = 144, ["frameWidth"] = 33, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PETTHEEDDIE.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "WeebRun.tga"] = {["nFrames"] = 8, ["frameWidth"] = 29, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "mirkoTempting.tga"] = {["nFrames"] = 19, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "POGGIED.tga"] = {["nFrames"] = 27, ["frameWidth"] = 65, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SPRAY.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "FLASHBANG.tga"] = {["nFrames"] = 25, ["frameWidth"] = 74, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "lookBoth.tga"] = {["nFrames"] = 19, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PointAndLaugh.tga"] = {["nFrames"] = 17, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BASED.tga"] = {["nFrames"] = 82, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "LEAKERS.tga"] = {["nFrames"] = 7, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "furryRun.tga"] = {["nFrames"] = 117, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "HACKERMANs.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "hackerCD.tga"] = {["nFrames"] = 102, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "MYEYES.tga"] = {["nFrames"] = 43, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Saved.tga"] = {["nFrames"] = 48, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Smadging.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "RemFlick.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "redsiren.tga"] = {["nFrames"] = 17, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "baguettespin.tga"] = {["nFrames"] = 7, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "POGGIEs.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "peepoHackies.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "choccyGlorp.tga"] = {["nFrames"] = 95, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ScaredKitten.tga"] = {["nFrames"] = 55, ["frameWidth"] = 30, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "CUMMIES.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "pepeSTABBY.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SkillIssue.tga"] = {["nFrames"] = 7, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MYAAA.tga"] = {["nFrames"] = 29, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BLANKIES.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "BANNED.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "WideBoobaMicrowavege.tga"] = {["nFrames"] = 14, ["frameWidth"] = 58, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DvaAss.tga"] = {["nFrames"] = 59, ["frameWidth"] = 57, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "wideVIBE.tga"] = {["nFrames"] = 118, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "GroupWankge.tga"] = {["nFrames"] = 2, ["frameWidth"] = 92, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "moon2NERD.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "POOTERS.tga"] = {["nFrames"] = 25, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "HYPERROBDAB.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "PUSSA.tga"] = {["nFrames"] = 186, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Dooma.tga"] = {["nFrames"] = 15, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GOTTEM.tga"] = {["nFrames"] = 52, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "WelcomeToTheClubBuddy.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AREYOUAGIRL.tga"] = {["nFrames"] = 55, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BEGGING.tga"] = {["nFrames"] = 251, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MyHonestReaction.tga"] = {["nFrames"] = 21, ["frameWidth"] = 31, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ppFall.tga"] = {["nFrames"] = 25, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CATBEDOINGTHELAUNDRY.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Hai.tga"] = {["nFrames"] = 2, ["frameWidth"] = 46, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 64, ["framerate"] = 3}
TwitchEmotes_animation_metadata[basePath .. "YouGotMe.tga"] = {["nFrames"] = 104, ["frameWidth"] = 51, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "uuh.tga"] = {["nFrames"] = 41, ["frameWidth"] = 57, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "buh.tga"] = {["nFrames"] = 98, ["frameWidth"] = 45, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ELPERMASSACRE.tga"] = {["nFrames"] = 58, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "plink.tga"] = {["nFrames"] = 59, ["frameWidth"] = 80, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "moon2Gamba.tga"] = {["nFrames"] = 59, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "glorpShakey.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Whitemane.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "moon2WGIF.tga"] = {["nFrames"] = 50, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "gachiHop.tga"] = {["nFrames"] = 49, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "gachiGold.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "gachiOnFire.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "gachiBOP.tga"] = {["nFrames"] = 20, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "gachiW.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "OOOO.tga"] = {["nFrames"] = 21, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Joel.tga"] = {["nFrames"] = 36, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "WHAT.tga"] = {["nFrames"] = 55, ["frameWidth"] = 33, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "glorpHai.tga"] = {["nFrames"] = 2, ["frameWidth"] = 46, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 64, ["framerate"] = 3}
TwitchEmotes_animation_metadata[basePath .. "meandyouhorny.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "IHATEYOU.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "slorpglorp.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "BRB.tga"] = {["nFrames"] = 1, ["frameWidth"] = 33, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DIDSOMEONESAYGLORP.tga"] = {["nFrames"] = 63, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "Mglorpy.tga"] = {["nFrames"] = 44, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "VeryGlorp.tga"] = {["nFrames"] = 95, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "PauseSNIPER.tga"] = {["nFrames"] = 1, ["frameWidth"] = 80, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Crungo.tga"] = {["nFrames"] = 69, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "WAITWAITWAIT.tga"] = {["nFrames"] = 172, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "CatDriving.tga"] = {["nFrames"] = 184, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SEETHE.tga"] = {["nFrames"] = 60, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "glorpCHAT.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PIZZA.tga"] = {["nFrames"] = 50, ["frameWidth"] = 31, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "PUPW.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "OfCourse.tga"] = {["nFrames"] = 49, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "sillyChamp.tga"] = {["nFrames"] = 50, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Dodge.tga"] = {["nFrames"] = 115, ["frameWidth"] = 57, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "PISSIN.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 7}
TwitchEmotes_animation_metadata[basePath .. "AnkhaPls.tga"] = {["nFrames"] = 51, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ABOBA.tga"] = {["nFrames"] = 81, ["frameWidth"] = 69, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 40}
TwitchEmotes_animation_metadata[basePath .. "campfire.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "Pressed.tga"] = {["nFrames"] = 75, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "LETHIMSHAKEY.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "MMMM.tga"] = {["nFrames"] = 44, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "beyumiJAM.tga"] = {["nFrames"] = 60, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "GlorpMeeting.tga"] = {["nFrames"] = 7, ["frameWidth"] = 77, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DOCING.tga"] = {["nFrames"] = 101, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "DITTO.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "Shrug.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Gregory.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 1}
TwitchEmotes_animation_metadata[basePath .. "docnotL.tga"] = {["nFrames"] = 60, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "docRant.tga"] = {["nFrames"] = 74, ["frameWidth"] = 48, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CatTime.tga"] = {["nFrames"] = 155, ["frameWidth"] = 21, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ASSEMBLE.tga"] = {["nFrames"] = 32, ["frameWidth"] = 93, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 16}
TwitchEmotes_animation_metadata[basePath .. "SCATTER.tga"] = {["nFrames"] = 16, ["frameWidth"] = 93, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 512, ["framerate"] = 16}
TwitchEmotes_animation_metadata[basePath .. "GAWKGAWK.tga"] = {["nFrames"] = 7, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BBoomer.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "LETSGOOOO.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "peepoNaruSprint.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "VANiSH.tga"] = {["nFrames"] = 38, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GIGARICH.tga"] = {["nFrames"] = 106, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "VeryFunny.tga"] = {["nFrames"] = 121, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MinorSpellingError.tga"] = {["nFrames"] = 166, ["frameWidth"] = 56, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "CRAWLERS.tga"] = {["nFrames"] = 21, ["frameWidth"] = 47, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "GuitarTime.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "HYPERRACC.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "PUKERS.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "pepeJAM.tga"] = {["nFrames"] = 15, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "sonicW.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "peepoPothole.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "Shitti.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 4}
TwitchEmotes_animation_metadata[basePath .. "peepoFlute.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 4}
TwitchEmotes_animation_metadata[basePath .. "knucklesW.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "Homi.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "pepeNuke.tga"] = {["nFrames"] = 131, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "bunnyJAM.tga"] = {["nFrames"] = 250, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "fishJAM.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "baldYikes.tga"] = {["nFrames"] = 128, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Sneak.tga"] = {["nFrames"] = 14, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "mhm.tga"] = {["nFrames"] = 9, ["frameWidth"] = 37, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 512, ["framerate"] = 4}
TwitchEmotes_animation_metadata[basePath .. "NUKE.tga"] = {["nFrames"] = 31, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NOIDONTTHINKSO.tga"] = {["nFrames"] = 124, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "catPunchU.tga"] = {["nFrames"] = 102, ["frameWidth"] = 34, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 24}
TwitchEmotes_animation_metadata[basePath .. "catCheck.tga"] = {["nFrames"] = 68, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "BANERS.tga"] = {["nFrames"] = 2, ["frameWidth"] = 33, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 64, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "GlorpSpin.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "floppy.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "autismGathering.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "HuggingInEarthquake.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "OOOOO.tga"] = {["nFrames"] = 90, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "floppygang.tga"] = {["nFrames"] = 10, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "GlueTime.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "AGGREND.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "Sigma.tga"] = {["nFrames"] = 41, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "sigmaArrive.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "GoodTake.tga"] = {["nFrames"] = 25, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "RODL.tga"] = {["nFrames"] = 3, ["frameWidth"] = 39, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 128, ["framerate"] = 2}
TwitchEmotes_animation_metadata[basePath .. "aaAAAAAaaaaaaaAAAAAaaaaaaaAAAAAa.tga"] = {["nFrames"] = 3, ["frameWidth"] = 37, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Salami.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "IVEGONEPASTHEPOINTOFINSANITY.tga"] = {["nFrames"] = 64, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AshTwerk.tga"] = {["nFrames"] = 23, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "LTGNOW.tga"] = {["nFrames"] = 90, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SpringlesLong.tga"] = {["nFrames"] = 6, ["frameWidth"] = 74, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 256, ["framerate"] = 6}
TwitchEmotes_animation_metadata[basePath .. "ViolinTime.tga"] = {["nFrames"] = 25, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "500Cigarettes.tga"] = {["nFrames"] = 146, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "peepoBox.tga"] = {["nFrames"] = 76, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DinkDong.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BUSSERS.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GokuGriddy.tga"] = {["nFrames"] = 38, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "SnakeTwerk.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SpiderTwerk.tga"] = {["nFrames"] = 47, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "spidermanAssAssClap.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "HUHBibi.tga"] = {["nFrames"] = 1, ["frameWidth"] = 30, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "LETHIMPOOP.tga"] = {["nFrames"] = 10, ["frameWidth"] = 41, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 512, ["framerate"] = 0}

TwitchEmotes_animation_metadata[basePath .. "glorpDrive.tga"] = {["nFrames"] = 51, ["frameWidth"] = 73, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NuggetDance.tga"] = {["nFrames"] = 240, ["frameWidth"] = 42, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "GIGAGEDIGEDAGEDAGO.tga"] = {["nFrames"] = 199, ["frameWidth"] = 48, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SoulShroom.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "ricardoFlick.tga"] = {["nFrames"] = 128, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SHITTERS.tga"] = {["nFrames"] = 123, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "DEVIOUS.tga"] = {["nFrames"] = 21, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "tuh.tga"] = {["nFrames"] = 192, ["frameWidth"] = 35, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Smoeg.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PoroDisco.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "VINDICTA.tga"] = {["nFrames"] = 3, ["frameWidth"] = 51, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 128, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "WideAmongUsGaySex.tga"] = {["nFrames"] = 7, ["frameWidth"] = 88, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 256, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "jorkin.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Listening.tga"] = {["nFrames"] = 162, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "gettingSturdy.tga"] = {["nFrames"] = 126, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "GotCaughtTrolling.tga"] = {["nFrames"] = 203, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "NotMyStreamer.tga"] = {["nFrames"] = 39, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "HUMPERS.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "billyDrinking.tga"] = {["nFrames"] = 169, ["frameWidth"] = 42, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardcaststeleportation.tga"] = {["nFrames"] = 90, ["frameWidth"] = 43, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardblicky.tga"] = {["nFrames"] = 75, ["frameWidth"] = 43, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "notListening.tga"] = {["nFrames"] = 162, ["frameWidth"] = 56, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SayGex.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardgoestobed.tga"] = {["nFrames"] = 59, ["frameWidth"] = 31, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardblicky2.tga"] = {["nFrames"] = 38, ["frameWidth"] = 40, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardsummonsacow.tga"] = {["nFrames"] = 60, ["frameWidth"] = 34, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardpowersup.tga"] = {["nFrames"] = 38, ["frameWidth"] = 40, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardfliesaway.tga"] = {["nFrames"] = 60, ["frameWidth"] = 40, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardcastsblizzard.tga"] = {["nFrames"] = 90, ["frameWidth"] = 43, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fatasswizardcastsbanishment.tga"] = {["nFrames"] = 69, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "zazaglorp.tga"] = {["nFrames"] = 90, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "cokeglorp.tga"] = {["nFrames"] = 99, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "aimbert.tga"] = {["nFrames"] = 25, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "zazabert.tga"] = {["nFrames"] = 90, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "cokebert.tga"] = {["nFrames"] = 99, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "stickBugged.tga"] = {["nFrames"] = 19, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "AAUGH.tga"] = {["nFrames"] = 100, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "sabrinaPls.tga"] = {["nFrames"] = 129, ["frameWidth"] = 36, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "glorpFeet.tga"] = {["nFrames"] = 54, ["frameWidth"] = 54, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 30}
