basePath = "Interface\\AddOns\\TwitchEmotes_Giga\\emotes\\";
TwitchEmotes_animation_metadata[basePath .. "peepoRun.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18};
TwitchEmotes_animation_metadata[basePath .. "donkWalk.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "catPls.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Cooking.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MONKE.tga"] = {["nFrames"] = 158, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "SCHIZO.tga"] = {["nFrames"] = 71, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "catYep.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "catNope.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "LETSFUCKINGSHIT.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GAMBA.tga"] = {["nFrames"] = 29, ["frameWidth"] = 32, ["frameHeight"] = 27, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "clam.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "THEVOICES.tga"] = {["nFrames"] = 45, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ppOverheat.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 28, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "HECOOKING.tga"] = {["nFrames"] = 38, ["frameWidth"] = 32, ["frameHeight"] = 31, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "THINKING.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "treeDance.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 20}
TwitchEmotes_animation_metadata[basePath .. "GAGGERS.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "awaree.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "Joeling.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 24}
TwitchEmotes_animation_metadata[basePath .. "donut.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "deadlole.tga"] = {["nFrames"] = 71, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DIEEE.tga"] = {["nFrames"] = 86, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "OFHELL.tga"] = {["nFrames"] = 22, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PotChamp.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 8}
TwitchEmotes_animation_metadata[basePath .. "POGCRAZY.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 8}
TwitchEmotes_animation_metadata[basePath .. "EATO.tga"] = {["nFrames"] = 65, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ChugU.tga"] = {["nFrames"] = 54, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "DESKCHAN.tga"] = {["nFrames"] = 15, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "chickenWalk.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "NAUR.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NOOO.tga"] = {["nFrames"] = 5, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "JOHNSOULS.tga"] = {["nFrames"] = 81, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "docPls.tga"] = {["nFrames"] = 126, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "RapThis.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "LICKA.tga"] = {["nFrames"] = 58, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "GETALIFE.tga"] = {["nFrames"] = 31, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Tssk.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "borpaSpin.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "pikaMine.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "LondonStyle.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 4}
TwitchEmotes_animation_metadata[basePath .. "DIESOFCRINGE.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "RobPls.tga"] = {["nFrames"] = 50, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Nessie.tga"] = {["nFrames"] = 106, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MODS.tga"] = {["nFrames"] = 86, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Fishinge.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "Gachi.tga"] = {["nFrames"] = 179, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 40}
TwitchEmotes_animation_metadata[basePath .. "SurefourHittingDaGriddy.tga"] = {["nFrames"] = 179, ["frameWidth"] = 128, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "moon2Lies.tga"] = {["nFrames"] = 26, ["frameWidth"] = 66, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "TAUNTED.tga"] = {["nFrames"] = 88, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SEXO.tga"] = {["nFrames"] = 65, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "PawgChamp.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "MilkTime.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "Goon.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GachiVictory.tga"] = {["nFrames"] = 14, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "gachiCOOL.tga"] = {["nFrames"] = 13, ["frameWidth"] = 29, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 40}
TwitchEmotes_animation_metadata[basePath .. "buttGala.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 7}
TwitchEmotes_animation_metadata[basePath .. "YES.tga"] = {["nFrames"] = 33, ["frameWidth"] = 43, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "NOPE.tga"] = {["nFrames"] = 36, ["frameWidth"] = 40, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Bocchi.tga"] = {["nFrames"] = 32, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Lick.tga"] = {["nFrames"] = 31, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Kissahomie.tga"] = {["nFrames"] = 29, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "dpsCheck.tga"] = {["nFrames"] = 28, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "blobSweating.tga"] = {["nFrames"] = 80, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "BaldiPls.tga"] = {["nFrames"] = 205, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DONOTCUM.tga"] = {["nFrames"] = 46, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "IMGONNACUM.tga"] = {["nFrames"] = 50, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SHEESH.tga"] = {["nFrames"] = 98, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ROFL.tga"] = {["nFrames"] = 40, ["frameWidth"] = 40, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GRATZ.tga"] = {["nFrames"] = 144, ["frameWidth"] = 33, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PETTHEEDDIE.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "WeebRun.tga"] = {["nFrames"] = 8, ["frameWidth"] = 29, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "mirkoTempting.tga"] = {["nFrames"] = 19, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "POGGIED.tga"] = {["nFrames"] = 27, ["frameWidth"] = 65, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SPRAY.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "FLASHBANG.tga"] = {["nFrames"] = 25, ["frameWidth"] = 74, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "lookBoth.tga"] = {["nFrames"] = 19, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PointAndLaugh.tga"] = {["nFrames"] = 17, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BASED.tga"] = {["nFrames"] = 82, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "LEAKERS.tga"] = {["nFrames"] = 7, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "furryRun.tga"] = {["nFrames"] = 117, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "HACKERMANs.tga"] = {["nFrames"] = 11, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "hackerCD.tga"] = {["nFrames"] = 102, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "MYEYES.tga"] = {["nFrames"] = 43, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Saved.tga"] = {["nFrames"] = 48, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Smadging.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "RemFlick.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "redsiren.tga"] = {["nFrames"] = 17, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "baguettespin.tga"] = {["nFrames"] = 7, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "POGGIEs.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 14}
TwitchEmotes_animation_metadata[basePath .. "peepoHackies.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "choccyGlorp.tga"] = {["nFrames"] = 95, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ScaredKitten.tga"] = {["nFrames"] = 55, ["frameWidth"] = 30, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "CUMMIES.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "pepeSTABBY.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "SkillIssue.tga"] = {["nFrames"] = 7, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MYAAA.tga"] = {["nFrames"] = 29, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BLANKIES.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "BANNED.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "LETHIMPOOP.tga"] = {["nFrames"] = 10, ["frameWidth"] = 41, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 512, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "HornyLicense.tga"] = {["nFrames"] = 1, ["frameWidth"] = 41, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 32, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "WideBoobaMicrowavege.tga"] = {["nFrames"] = 14, ["frameWidth"] = 58, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DvaAss.tga"] = {["nFrames"] = 59, ["frameWidth"] = 57, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Handshakege.tga"] = {["nFrames"] = 1, ["frameWidth"] = 49, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 32, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "wideVIBE.tga"] = {["nFrames"] = 118, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 4096, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "GroupWankge.tga"] = {["nFrames"] = 2, ["frameWidth"] = 92, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "moon2NERD.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "POOTERS.tga"] = {["nFrames"] = 25, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "HYPERROBDAB.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 9}
TwitchEmotes_animation_metadata[basePath .. "PUSSA.tga"] = {["nFrames"] = 186, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Dooma.tga"] = {["nFrames"] = 15, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GOTTEM.tga"] = {["nFrames"] = 52, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "WelcomeToTheClubBuddy.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AREYOUAGIRL.tga"] = {["nFrames"] = 55, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BEGGING.tga"] = {["nFrames"] = 251, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MyHonestReaction.tga"] = {["nFrames"] = 21, ["frameWidth"] = 31, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ppFall.tga"] = {["nFrames"] = 25, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CATBEDOINGTHELAUNDRY.tga"] = {["nFrames"] = 53, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "War.tga"] = {["nFrames"] = 1, ["frameWidth"] = 62, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 32, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "slayyy.tga"] = {["nFrames"] = 1, ["frameWidth"] = 45, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 32, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "Hai.tga"] = {["nFrames"] = 2, ["frameWidth"] = 46, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 64, ["framerate"] = 3}
TwitchEmotes_animation_metadata[basePath .. "YouGotMe.tga"] = {["nFrames"] = 104, ["frameWidth"] = 51, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "uuh.tga"] = {["nFrames"] = 41, ["frameWidth"] = 57, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "buh.tga"] = {["nFrames"] = 98, ["frameWidth"] = 45, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CAUGHT.tga"] = {["nFrames"] = 1, ["frameWidth"] = 61, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 32, ["framerate"] = 0}
TwitchEmotes_animation_metadata[basePath .. "ELPERMASSACRE.tga"] = {["nFrames"] = 58, ["frameWidth"] = 96, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "plink.tga"] = {["nFrames"] = 59, ["frameWidth"] = 80, ["frameHeight"] = 32, ["imageWidth"] = 128, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "moon2Gamba.tga"] = {["nFrames"] = 59, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 64, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "glorpShakey.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
